spring.application.name=gestiongastos

# --- CONEXION A AIVEN (Asegurate que termine con useSSL=true) ---
spring.datasource.url=jdbc:mysql://mysql-2ced17db-tsosa416-540f.h.aivencloud.com:10475/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_QjnnZffR9PTbcN7dNlD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Esto evita que la app explote si no se puede conectar al instante
spring.datasource.continue-on-error=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- PUERTO Y SEGURIDAD ---
server.port=8080
jwt.secret=mi_clave_secreta_super_segura_que_deberia_ser_mas_larga_aun_1234567890
jwt.expiration=14400000